# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_acqiris', [dirname(__file__)])
        except ImportError:
            import _acqiris
            return _acqiris
        if fp is not None:
            try:
                _mod = imp.load_module('_acqiris', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _acqiris = swig_import_helper()
    del swig_import_helper
else:
    import _acqiris
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class BifurcationMap(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, BifurcationMap, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, BifurcationMap, name)
    __repr__ = _swig_repr
    __swig_destroy__ = _acqiris.delete_BifurcationMap
    __del__ = lambda self : None;
    def __init__(self): 
        this = _acqiris.new_BifurcationMap()
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["rotation"] = _acqiris.BifurcationMap_rotation_set
    __swig_getmethods__["rotation"] = _acqiris.BifurcationMap_rotation_get
    if _newclass:rotation = _swig_property(_acqiris.BifurcationMap_rotation_get, _acqiris.BifurcationMap_rotation_set)
    __swig_setmethods__["costable"] = _acqiris.BifurcationMap_costable_set
    __swig_getmethods__["costable"] = _acqiris.BifurcationMap_costable_get
    if _newclass:costable = _swig_property(_acqiris.BifurcationMap_costable_get, _acqiris.BifurcationMap_costable_set)
    __swig_setmethods__["sintable"] = _acqiris.BifurcationMap_sintable_set
    __swig_getmethods__["sintable"] = _acqiris.BifurcationMap_sintable_get
    if _newclass:sintable = _swig_property(_acqiris.BifurcationMap_sintable_get, _acqiris.BifurcationMap_sintable_set)
    __swig_setmethods__["rotatedWaveform"] = _acqiris.BifurcationMap_rotatedWaveform_set
    __swig_getmethods__["rotatedWaveform"] = _acqiris.BifurcationMap_rotatedWaveform_get
    if _newclass:rotatedWaveform = _swig_property(_acqiris.BifurcationMap_rotatedWaveform_get, _acqiris.BifurcationMap_rotatedWaveform_set)
    __swig_setmethods__["means"] = _acqiris.BifurcationMap_means_set
    __swig_getmethods__["means"] = _acqiris.BifurcationMap_means_get
    if _newclass:means = _swig_property(_acqiris.BifurcationMap_means_get, _acqiris.BifurcationMap_means_set)
    __swig_setmethods__["trends"] = _acqiris.BifurcationMap_trends_set
    __swig_getmethods__["trends"] = _acqiris.BifurcationMap_trends_get
    if _newclass:trends = _swig_property(_acqiris.BifurcationMap_trends_get, _acqiris.BifurcationMap_trends_set)
    __swig_setmethods__["averages"] = _acqiris.BifurcationMap_averages_set
    __swig_getmethods__["averages"] = _acqiris.BifurcationMap_averages_get
    if _newclass:averages = _swig_property(_acqiris.BifurcationMap_averages_get, _acqiris.BifurcationMap_averages_set)
    __swig_setmethods__["probabilities"] = _acqiris.BifurcationMap_probabilities_set
    __swig_getmethods__["probabilities"] = _acqiris.BifurcationMap_probabilities_get
    if _newclass:probabilities = _swig_property(_acqiris.BifurcationMap_probabilities_get, _acqiris.BifurcationMap_probabilities_set)
    __swig_setmethods__["crossProbabilities"] = _acqiris.BifurcationMap_crossProbabilities_set
    __swig_getmethods__["crossProbabilities"] = _acqiris.BifurcationMap_crossProbabilities_get
    if _newclass:crossProbabilities = _swig_property(_acqiris.BifurcationMap_crossProbabilities_get, _acqiris.BifurcationMap_crossProbabilities_set)
    __swig_setmethods__["nPoints"] = _acqiris.BifurcationMap_nPoints_set
    __swig_getmethods__["nPoints"] = _acqiris.BifurcationMap_nPoints_get
    if _newclass:nPoints = _swig_property(_acqiris.BifurcationMap_nPoints_get, _acqiris.BifurcationMap_nPoints_set)
    __swig_setmethods__["nSegments"] = _acqiris.BifurcationMap_nSegments_set
    __swig_getmethods__["nSegments"] = _acqiris.BifurcationMap_nSegments_get
    if _newclass:nSegments = _swig_property(_acqiris.BifurcationMap_nSegments_get, _acqiris.BifurcationMap_nSegments_set)
    __swig_setmethods__["activeChannels"] = _acqiris.BifurcationMap_activeChannels_set
    __swig_getmethods__["activeChannels"] = _acqiris.BifurcationMap_activeChannels_get
    if _newclass:activeChannels = _swig_property(_acqiris.BifurcationMap_activeChannels_get, _acqiris.BifurcationMap_activeChannels_set)
    __swig_setmethods__["index"] = _acqiris.BifurcationMap_index_set
    __swig_getmethods__["index"] = _acqiris.BifurcationMap_index_get
    if _newclass:index = _swig_property(_acqiris.BifurcationMap_index_get, _acqiris.BifurcationMap_index_set)
    __swig_setmethods__["nLoops"] = _acqiris.BifurcationMap_nLoops_set
    __swig_getmethods__["nLoops"] = _acqiris.BifurcationMap_nLoops_get
    if _newclass:nLoops = _swig_property(_acqiris.BifurcationMap_nLoops_get, _acqiris.BifurcationMap_nLoops_set)
    def setRotation(self, *args): return _acqiris.BifurcationMap_setRotation(self, *args)
    def init(self): return _acqiris.BifurcationMap_init(self)
    def add(self, *args): return _acqiris.BifurcationMap_add(self, *args)
    def finish(self): return _acqiris.BifurcationMap_finish(self)
BifurcationMap_swigregister = _acqiris.BifurcationMap_swigregister
BifurcationMap_swigregister(BifurcationMap)



